// src/app/layout.tsx
import type { Metadata } from "next";
import Navigation from "../components/Navigation";

// Import global CSS and Google Font
import "../styles/globals.css";
import { League_Spartan } from "next/font/google";
import { NetflixFooter } from "@/components/Footer";

// Load font
const neuton = League_Spartan({ subsets: ["latin"], weight: "400" });

// Metadata for SEO
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Root layout component
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${neuton.className} antialiased select-none duration-300`}>
        <Navigation />
        <main>{children}</main>
        <NetflixFooter />
        <div id="modal-root" />
      </body>
    </html>
  );
}
